package autoswitch

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

type AuthAccount struct {
	Host  string `json:"host"`
	Login string `json:"login"`
}

func DiscoverAccounts(ghPath string, runner CommandRunner) ([]AuthAccount, error) {
	data, err := runner.Output(ghPath, "auth", "status", "--json", "hosts")
	if err != nil {
		return nil, fmt.Errorf("read authenticated accounts with `%s auth status`: %w", ghPath, err)
	}
	var response struct {
		Hosts map[string][]struct {
			Login string `json:"login"`
		} `json:"hosts"`
	}
	if err := json.Unmarshal(data, &response); err != nil {
		return nil, fmt.Errorf("decode gh auth status: %w", err)
	}
	var accounts []AuthAccount
	for host, entries := range response.Hosts {
		for _, entry := range entries {
			if host != "" && entry.Login != "" {
				accounts = append(accounts, AuthAccount{Host: host, Login: entry.Login})
			}
		}
	}
	sort.Slice(accounts, func(i, j int) bool {
		if accounts[i].Host == accounts[j].Host {
			return accounts[i].Login < accounts[j].Login
		}
		return accounts[i].Host < accounts[j].Host
	})
	if len(accounts) == 0 {
		return nil, fmt.Errorf("gh reported no authenticated accounts; run `gh auth login` first")
	}
	return accounts, nil
}

func RenderConfig(accounts []AuthAccount) string {
	var out strings.Builder
	out.WriteString("# Generated by gh-account-autoswitch. Rules are checked in order.\n")
	out.WriteString("# Replace the suggested owner expressions or add directory/remote matchers.\n")
	out.WriteString("version = 1\n")
	for _, account := range accounts {
		fmt.Fprintf(&out, "\n[[rules]]\nname = %q\naccount = %q\nhost = %q\nowner = %q\n", account.Login+" on "+account.Host, account.Login, account.Host, "^"+regexpQuote(account.Login)+"$")
	}
	return out.String()
}

func regexpQuote(value string) string {
	const meta = `\.+*?()|[]{}^$`
	var out strings.Builder
	for _, char := range value {
		if strings.ContainsRune(meta, char) {
			out.WriteRune('\\')
		}
		out.WriteRune(char)
	}
	return out.String()
}
